In [61]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv("data/iris.csv")
df

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [63]:
previsores = df.iloc[:, :4].values
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [64]:
classes = df.iloc[:, -1].values
classes

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

Como a rede neural não entende variavel categorica, temos que converter as possiveis classes em números:
      
      - 0 = Iris-setosa;
      - 1 = Iris-versicolor;
      - 2 = Iris-virginica;
   

In [65]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

labelenconder = LabelEncoder()
classes = labelenconder.fit_transform(classes)
classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Transformando o dado de 1 dimensão para 3, seguindo a saída da rede neural
 - 1 0 0 = Iris-setosa;
 - 0 1 0 = Iris-versicolor;
 - 0 0 1 = Iris-virginica;

In [66]:
classes_dummy = to_categorical(classes)
classes_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train, X_test, y_train, y_test = train_test_split(previsores, classes_dummy, test_size=0.25)

In [69]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [87]:
def createNetwork():
    model = Sequential()
    model.add(Dense(units=10, activation="relu", input_dim=4))
    model.add(Dense(units=3, activation="softmax"))
    model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
    model_json = model.to_json()
    with open("model_iris.json","w") as json_file:
        json_file.write(model_json)
    return model

In [88]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

model = KerasClassifier(build_fn=createNetwork, batch_size=5, epochs=200)

In [ ]:
results = cross_val_score(estimator=model, X=previsores, y=classes, cv=10, scoring="accuracy")
average = results.mean()
print(average)
desvio_padrao = results.std()
print(desvio_padrao)

In [92]:
model = Sequential()
model.add(Dense(units=10, activation="relu", input_dim=4))
model.add(Dense(units=3, activation="softmax"))
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(previsores, classes_dummy, batch_size=10, epochs=200)

Epoch 1/200
15/15 [==============================] - 0s 1ms/step - loss: 3.6289 - accuracy: 0.3689
Epoch 2/200
15/15 [==============================] - 0s 1ms/step - loss: 3.3835 - accuracy: 0.3254
Epoch 3/200
15/15 [==============================] - 0s 1ms/step - loss: 2.9358 - accuracy: 0.3330
Epoch 4/200
15/15 [==============================] - 0s 1ms/step - loss: 2.6517 - accuracy: 0.3143
Epoch 5/200
15/15 [==============================] - 0s 1ms/step - loss: 2.4169 - accuracy: 0.2672
Epoch 6/200
15/15 [==============================] - 0s 1ms/step - loss: 1.7410 - accuracy: 0.3460
Epoch 7/200
15/15 [==============================] - 0s 1ms/step - loss: 1.5251 - accuracy: 0.3283
Epoch 8/200
15/15 [==============================] - 0s 1ms/step - loss: 1.2012 - accuracy: 0.3198
Epoch 9/200
15/15 [==============================] - 0s 1ms/step - loss: 1.0524 - accuracy: 0.3478
Epoch 10/200
15/15 [==============================] - 0s 1ms/step - loss: 0.9130 - accuracy: 0.4417
Epoch 11/

In [99]:
model_json = model.to_json()
#salvando as configuracoes
with open("model_iris.json","w") as json_file:
    json_file.write(model_json)
    
#salvando os pesos
model.save_weights("model_weights.h5")

In [100]:
result = model.evaluate(previsores, classes_dummy)


5/5 [==============================] - 0s 2ms/step - loss: 0.1040 - accuracy: 0.9800


In [110]:
previsoes = model.predict(previsores)
previsoes = [np.argmax(t) for t in previsoes]

In [108]:
y_test_labed = [np.argmax(t) for t in classes_dummy]

In [109]:
from sklearn.metrics import confusion_matrix

confusion_matrix(previsoes, y_test_labed)

array([[50,  0,  0],
       [ 0, 48,  1],
       [ 0,  2, 49]])